export enum FileType {
	AUDIO = 1,
	TEXTURE = 2,
	VIDEO = 3,
	ASSET_BUNDLE = 4,
	TEXT = 5,
	APPLICATION_ICON = 6,
	PRODUCT_DETAIL_PAGE_ART = 7,
	SCREENSHOT = 8,
	VIDEO_TRAILER = 9,
	STORE_LANDSCAPE_ICON = 10,
	IMAGE_GALLERY = 11,
	SQUARE_LOGO = 12,
	LONG_LOGO = 13
}
